### ISSUE TITLE
where are the HTML/CSS?

### ISSUE THREAD

**Issue by yairEO** [Dudemullet/generator-d3-iris#1]
`I left all the html/css/js in a single to make it easier to`

what does that even mean?

**Comment by Dudemullet** [comment]
> where are the HTML/CSS?

Every time you create a new example via `yo d3-iris:new <name>` or `yo d3-iris:adv <name>`. A folder is created inside the app directory with the `<name>` you gave it through the cli. In that folder you can find the `index.html` file for that example.

> what does that even mean?

Sorry for the confusion but what I meant to say is that I left placeholder css and javascript blocks **in** the `index.html` file instead of separating them into their own file.

Does this answer your question?
